# Generated by Django 4.1.3 on 2022-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAwsCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aws_access_key_id", models.CharField(max_length=250)),
                ("aws_secret_access_key", models.CharField(max_length=250)),
                ("region_name", models.CharField(max_length=250)),
                ("bucket_name", models.CharField(max_length=250)),
            ],
        ),
    ]
